# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742
print("The diameter of {}is {} kilometers".format(planet,diameter) )

The diameter of Earthis 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
import numpy as np
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [14]:
a=np.arange(20,36,2)
a

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
s=np.arange(0,9).reshape(3,3)
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
s=np.concatenate((a,b),axis=0)
print(s)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd
d={"reg no":[1,2],"name":['ram','sita']}
df=pd.DataFrame(d)
df


reg no  name
0       1   ram
1       2  sita

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [20]:
s=pd.date_range(start='06-10-2022',end='06-10-2023')
s

DatetimeIndex(['2022-06-10', '2022-06-11', '2022-06-12', '2022-06-13',
               '2022-06-14', '2022-06-15', '2022-06-16', '2022-06-17',
               '2022-06-18', '2022-06-19',
               ...
               '2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04',
               '2023-06-05', '2023-06-06', '2023-06-07', '2023-06-08',
               '2023-06-09', '2023-06-10'],
              dtype='datetime64[ns]', length=366, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [22]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
 
df=pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24